- name: Load Nodejs
  ansible.builtin.include_role:
    name: common
    task_from: nodejs

- name: copy mognodb repo file
  ansible.builtin.copy:
    src: mongo.repo
    dest: etc/yum.repos.d/mongo.repo

- name: Install mongoDB 
  ansible.builtin.dnf:
    name: mongodb-mongosh
    state: installed

- name: Load Master data
  ansible.builtin.shell: mongosh --host mongo-dev.gvndevops12.tech </app/db/master-data.js


  


