
    
#     print_head download application content
#     curl -L -o /tmp/$component.zip https://roboshop-artifacts.s3.amazonaws.com/$component-v3.zip &>>$log_file
#     exit_status_print $?
#     cd /app 
    
#     print_head extract application content
#     unzip /tmp/catalogue.zip &>>$log_file
#     exit_status_print $?

- name: Add applicatioin user
  ansible.builtin.user:
    name: roboshop

- name:  Remove old app content
  ansible.builtin.file:
    path: /app
    state: absent

- name:  create an app content directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: download and extract app content
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/$component-v3.zip
    dest: /app
    remote_src: yes