# maven_app_setup(){
#     dnf install maven -y &>> $log_file
    
#     artifact_download
#     cd /app 

#     print_head install maven dependencies
#     mvn clean package  &>> $log_file
#     mv target/$component-1.0.jar $component.jar &>> $log_file

#     systemd_setup
# }


- name: Install maven
  ansible.builtin.dnf:
    name: maven
    state: installed

- name: Include artifact_download tasks
  ansible.builtin.include_tasks: artifact_download.yml

- name: Install Maven dependencies
  ansible.builtin.command:  mvn clean package ; mv target/{{ component_name }}-1.0.jar {{ component_name }}.jar 
  args:
    chdir: /app


- name: Include systemd_setup tasks
  ansible.builtin.include_tasks: systemd_setup.yml
