- name: Disable Node.js default module
  ansible.builtin.command: dnf module disable nodejs
  args:
    warn: false

- name: Enable Node.js 20 module
  ansible.builtin.command: dnf module enable nodejs:20
  args:
    warn: false

- name: Install Node.js
  ansible.builtin.dnf:
    name: nodejs
    state: installed

- name: Include artifact_download tasks
  ansible.builtin.include_tasks: artifact_download.yml

- name: Install Node.js dependencies
  ansible.builtin.command: npm install
  args:
    chdir: /app
    warn: false

- name: Include systemd_setup tasks
  ansible.builtin.include_tasks: systemd_setup.yml
