- name: Copy the sytemd service file
  ansible.builtin.copy:
    src: "{{component}}.service"
    dest: /etc/systemd/system/$component_name.service

- name: Start service
  ansible.builtin.systemd_service:
    name: "{{component_name}}"
    state: restarted
    enabled: yes
    daemon-reload: yes